services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: hexagon-sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: hexagon-rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

volumes:
  sql_data: